#JWT设置
jwt:
  #过期时间七天(秒)
  exp_time: 604800
  #验证主题
  sub: brave
  #（red_time）30天
  ref_time: 2592000

#权限管理
authority:
  auth: [ 'super','admin','user' ]
  super_admin: super
  admin: admin

#Blake设置
blake:
  #加盐
  salt: brave




