#JWT设置
jwt:
  #过期时间七天(秒)
  exp_time: 604800
  #验证主题(是被验证的是否当前服务的)
  sub: brave
  #（red_time）30天
  ref_time: 2592000

#权限管理
authority:
  #用于权限验证的数组，如果登陆权限没有禁止访问
  auth: [ 'super','admin','user' ]
  super_admin: super
  admin: admin

#Blake设置（密码加密）
blake:
  #加盐
  salt: brave

#邮箱地址设置（自己需要更改）
mail:
  mine_email: brave-rust@outlook.com
  smtp_server: smtp.office365.com
  password: aJxgopMLgmE33E
  port: 587






