[package]
name = "brave-core"
version = "0.1.0"
edition = "2021"
authors = ["Nueck <nueck@outlook.com>"]
repository = "https://github.com/Nueck/brave/"

#发布禁止
publish = false

[dependencies]
brave-utils = { path = "../brave-utils" }
brave-config = { path = "../brave-config" }
brave-home = { path = "../brave-home" }
brave-admin = { path = "../brave-admin" }
brave-blog = { path = "../brave-blog" }
brave-api = { path = "../brave-api" }
actix-web = "4.2.1"
actix-files = "0.6.2"
actix-rt = "2.8.0"
actix-cors = "0.6.4"
actix-web-lab = "0.19.1"
futures = "0.3.26"
futures-util = "0.3.26"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.93"
log = "0.4.17"
may = "0.3.41"
fast_log = "1.5.53"
dotenvy = "0.15.6"






